### PR TITLE
Use LEPTOS_BIN_TARGET_DIR for exe file

### PR DESCRIPTION
**Pull request by Raniz85**

### CODE REVIEW

**Comment by Raniz85** [comment]
Didn't catch this usage until I compiled in a clean workspace :/

**Comment by Raniz85** [comment]
It seems the new test is flaky due to parallell running, I'll see if I can come up with something to fix it.

**Comment by Raniz85** [comment]
I'll get back to this on monday - weekend starts now... Feel free to revert #151 if the tests are causing you grief in the meantime.

**Comment by Raniz85** [comment]
@gbj I removed the flaky test because getting it to work would require significant changes to how environment variables are picked up to be able to inject them in the tests without setting the environment for all tests.

Running with one test runner would also be a solution, but I don't like non-parallel tests for several reasons.

**Comment by akesson** [comment]
Yes, there's an important refactoring that I just don't find time to do to remove the use of CWD which screws up testing.

**Pull request merged**
