### PR TITLE
fix: use right artifact for binaryen in case of linux aarch64

### PR DESCRIPTION
**Pull request by morenol**

### CODE REVIEW

**Comment by benwis** [comment]
Thanks for the PR!

**Comment by morenol** [comment]
Your welcome, could you create a new release with this change?

**Comment by benwis** [comment]
Sure, I can do that a bit later today. Out of curiousity, what are you running aarch64 linux on?

**Comment by morenol** [comment]
A custom GitHub runner

**Comment by benwis** [comment]
@morenol A new version with that change has been released

**Pull request merged**
