### PR TITLE
cargo update

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

This is just a `cargo update` for wasm-windgen [v0.2.88](https://github.com/rustwasm/wasm-bindgen/releases/tag/0.2.88), to fix an issue similar to #129

### CODE REVIEW

**Comment by JoelBeicher** [comment]
Hey @nim65s I think those checks aren't going through due to the example projects.
The need to be updated to use the current leptos version 0.5, I think.

**Comment by gbj** [comment]
I think maybe you need to run `cargo update` in the two projects, so that they use wasm-bindgen 0.2.88 as well. You can see that their lockfiles have them at 0.2.87 still

https://github.com/leptos-rs/cargo-leptos/blob/0fbe4bb7c6773c696866eff5530c6c432bacc3fa/examples/project/Cargo.lock#L2820

**Comment by nim65s** [comment]
Thanks ! Let's try this.

**Comment by nim65s** [comment]
Now we have a test failure on windows related to path separators, but this test was already failing before this PR.

**Comment by gbj** [comment]
Thanks, looks good! Agreed we need to fix the Windows thing but it's not this PR.

**Pull request merged**
